# -*- coding: utf-8 -*-
"""Solution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gadv8oj4B1ruBXY8GwR6cQ9krbj311ZT
"""

arr = [1,5,7,8,5,3,4,2,1]
diff = -2

a = []

for i in range(len(arr) - 1, -1, -1):
  for j in range(len(arr) - 2, -1, -1):
    sub = arr[i] - arr[j]
    if sub == diff:
      a.append(arr[i])
      a.append(arr[j])
      i = j
      j = j
  break

if not a:
  a.append(arr[0])


for i in range(0,len(a)-1):
  for j in range(i+1,len(a)-1):
    if a[i] == a[j]:
      del a[j]
print(len(a))